# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: daily report

on:
  push:
    branches:
      - master
  schedule:
    - cron: "32 2 * * *"
  workflow_dispatch:

jobs:
  job1:
    name: daily report
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: do report
      run: |
        python ./dayReport.py -u ${{ secrets.CARD_NUM }} -p ${{ secrets.PASSWORD }}
    - name: get current date
      id: data
      run: echo "::set-output name=today::$(date +'%Y-%m-%d')"
    - name: send email
      uses: dawidd6/action-send-mail@master
      with:
        server_address: smtp.163.com
        server_port: 465
        username: ${{ secrets.MAIL_USERNAME }}
        password: ${{ secrets.MAIL_PASSWORD }}
        subject: SEU每日健康申报 ${{ steps.date.outputs.today }}
        body: file://email.txt
        to: 1764051293@qq.com
        from: GitHub Actions
        content_type: text/plain
